### ISSUE TITLE
unable to gem lake guardians

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Bugs-and-Issues#38] opened 2021-04-20 09:11 UTC
**Describe the Bug**
players are unable to gem the lake guardians (uxie, mesprit, azelf)

**To Reproduce**
get one of the lake guardians, be the OT, get it to level60 and 255happiness. then try to gem it (left click a ruby on them)

**Servers with the Bug**
all

**Expected behavior**
u should be able to gem them once

**Comment by Bruhbert1999** [comment] 2021-04-20 09:15
when using the /pokeedit command and changing the OT to myself, i'm able to gem them just fine

**Comment by HackuJacku** [comment] 2021-04-20 21:54
Tested with Uxie and Dialga and worked as intended, @Bruhbert1999. I'm slightly confused with that the issue is exactly, could you explain it more please?

**Comment by Bruhbert1999** [comment] 2021-04-21 08:22
if i take the poke the player is unable to gem and change the OT to myself, im perfectly fine to gem it myself (so without really changing anything). so i think it has smt to do with players not having perms maybe? or maybe its that they cant do it in claims etc (since admin can just ignore claims) ? cause in the last few weeks, there have been like 10ish tickets about not being able to gem lake guardians.

**Comment by HackuJacku** [comment] 2021-05-07 23:34
@Bruhbert1999 - I've tried to reproduce this and been unable to. Can you show me when you're next around please?

**Comment by HackuJacku** [comment] 2021-06-12 21:07
@Mikirae - can you take a look at this please? Unsure myself :/

**Comment by Mikirae** [comment] 2021-06-12 21:30
The only time I know that this happened, I've taken the mons, and for me, they say 254 happiness. It's been a few months since I've seen this though. Think we can close this as it's a Pixelmon bug regardless

**Closed by Mikirae** 2021-06-12 21:30 UTC
Labels: pixelmon
