### ISSUE TITLE
Multiple bugs/issues

### ISSUE THREAD

**Issue by ketl0rd** [SmashMC-Development/Bugs-and-Issues#1334] opened 2022-06-19 09:00 UTC
A few issues/bugs I would like to outline. 
1.  Opening PC causes game to crash, the only way to have a temporary fix to the issue is to completely restart the technic launcher. Not sure if this is an issue to players using the minecraft launcher. 
2. When placing obsidian into a blast furnace to smelt for Black Augurite, it does not work. The arrow will fill up however, there will be no item that is produced. This will continuously using coal as well until the fuel source is empty. 
3. Pokemon spawns in the overworld and inside of warzone are not correct I believe. Spawns are very rare in the overworld and do not seem correct. EG. I will receive multiple "ultra rare" tier spawns in biomes and no "rare" or "common" spawns. 
Warzone has the issue of not having anything spawn at all on multiple occasions of joining. Leaving myself in warzone for x amount of time with nothing to catch or do. 
All these issues I have come across while playing on the Rayquaza server, I hope they are looked into soon to make gameplay more enjoyable. 
IGN: ketl0rd 
Server Rayquaza

**Comment by manlybro2002** [comment] 2022-06-19 09:27
how much coal did you use? ive seen people use 11 lava buckets to smelt the obsidian

**Comment by Mikirae** [comment] 2022-06-21 06:38
I believe the first one might be caused by a Pokemon with glitched out EVs
I'm not sure how Black Augurite works, but it was supposed to be fixed in 9.0.2
When you see these ultra rare Pokemon, are they extremely high leveled? Like 75-100?

**Comment by Superfire96** [comment] 2022-08-26 02:21
Were fixed long time ago, closing old trackers.

**Closed as completed by Superfire96** 2022-08-26 02:21 UTC
