### ISSUE TITLE
Shrines not spawning legendary when provided with proper orb.

### ISSUE THREAD

**Issue by Jakejekel** [SmashMC-Development/Bugs-and-Issues#1575] opened 2022-12-11 22:09 UTC
**Describe the Bug**
The shrine in spawn, in this case the unused frozen shrine, when provided with the proper, filled orb, and the money, 
instead of taking the items and putting you in battle, instead puts into chat "Your orb is not compatible with the shrine"
**To Reproduce**
1. Go to 'shrines in spawn'
2. Click on 'frozen shrine with orb of frozen souls'
4. See error - Your orb is not compatible with the shrine.

**Servers with the Bug**
Please provide a list of which servers have this bug. only one I have knowledge of is groudin

**Expected behavior**
A clear and concise description of what you expected to happen. Expected to have the orb of frozen souls and 20k taken and be put in battle with Articuno.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![image](https://user-images.githubusercontent.com/120341268/206931696-cb988666-1f62-4369-a1cf-f899537fb351.png)

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
I am unsure if this is a bug for just me, or if it happens on the other servers. would be a good idea to look into it.

**Comment by Mikirae** [comment] 2022-12-12 05:20
The issue is that someone put down the wrong shrine. That's the Static Shrine.
It's now fixed :)

**Closed as completed by Mikirae** 2022-12-12 05:20 UTC
