### ISSUE TITLE
Rayquaza tournaments

### ISSUE THREAD

**Issue by LilAstrx** [SmashMC-Development/Bugs-and-Issues#904] opened 2021-12-04 21:41 UTC
on rayquaza the tournaments have not worked since the wipe/reset we are having to do rock paper scissors and u have to make a ticket if u win tournament as it does not give you the crate key

1. Go to 'Rayquaza tournament'
2. Click on 'well just join and u cant battle ur oponent '

only rayquaza i believe 

i expected for me to battle the person im up against in the tournament 

dont have any screenshots sadly

N/A

**Comment by HackuJacku** [comment] 2021-12-19 00:11
Duplicate of #887

**Closed as completed by HackuJacku** 2021-12-19 00:11 UTC
