### ISSUE TITLE
3rd Elite Four Challenge doesn't show up for E4 members

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Bugs-and-Issues#1105] opened 2022-01-30 00:37 UTC
**Describe the Bug**
When a challenger challenges the third elite 4 team the elite 4 member does not get a challenge request therefor not allowing them to accept the challenge.

**To Reproduce**
1) Beat first 2 elite 4 teams
2) /ag
3) queue into third e4 battle
4) e4 member does not receive challenge

**Servers with the Bug**
Kyogre

**Expected behavior**
Able to accept the challenge

**Comment by Rasgnarok** [comment] 2022-02-01 21:37
I just tested, can't reproduce. Have you tested selecting your team in /ag manage, and hitting 'SAVE', before receiving the challenge? Worked for me.

**Comment by Rasgnarok** [comment] 2022-02-01 21:38
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/1080

**Comment by Superfire96** [comment] 2022-04-16 00:33
Should be fixed

**Closed as completed by Superfire96** 2022-04-16 00:33 UTC
