### ISSUE TITLE
Safeplacing during battle

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Bugs-and-Issues#310] opened 2021-06-19 17:33 UTC
**Describe the Bug**
You can safeplace during battle (against a pokemon or a player) in warzone

**To Reproduce**
1. Go into warzone
2. Battle a player or a random pokemon
3. type /safeplace while in battle

**Servers with the Bug**
All servers that you have to wait 3 seconds in order to get out of warzone

**Expected behavior**
Shouldn't be able to safeplace in warzone.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84808660/122650819-ea8a3d00-d102-11eb-9622-9ced74b9f105.PNG)

**Additional context**
N/A

**Comment by HackuJacku** [comment] 2021-06-19 19:44
Duplicate of #306

**Closed as completed by HackuJacku** 2021-06-19 19:44 UTC
Labels: duplicate, pixelmon
