### ISSUE TITLE
The, once again, Illusive Boss tower

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#222] opened 2021-05-28 15:19 UTC
**Describe the Bug**
Unable to warp to boss tower

**To Reproduce**
1. type ./warp boss tower
2. get hit with the big NOPE

**Servers with the Bug**
Jirachi

**Expected behavior**
To be warped to boss tower.

**Screenshots**
'N/A'.

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment] 2021-05-28 23:19
Although I know what you mean, please state exactly what the issue is in the future. Fixed now.

**Closed as completed by HackuJacku** 2021-05-28 23:19 UTC
Labels: pixelmon
