### ISSUE TITLE
Duping doors

### ISSUE THREAD

**Issue by IronGolem19** [SmashMC-Development/Bugs-and-Issues#218] opened 2021-05-28 06:25 UTC
**Describe the Bug**
you are able to dupe doors in spawn 

**To Reproduce**
1. Go to spawn
2. Click on the leaf blocks around spawn 
3. spam right click any type of normal doors
4. then it dupes

**Servers with the Bug**
Please provide a list of which servers have this bug.
all servers.
**Expected behavior**
to not dupe doors
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
N/A

Add any other context about the problem here. If nothing, please add 'N/A'.
if needed i can show you how to do it

**Comment by HackuJacku** [comment] 2021-05-29 23:20
@IronGolem19 - I've been unable to reproduce this. Please can you provide some type of video please?

**Comment by IronGolem19** [comment] 2021-06-02 02:29
yea sorry i took so long  https://www.youtube.com/watch?v=VnjB_fXhDZA

**Comment by HackuJacku** [comment] 2021-10-15 19:35
Fixed on reset

**Closed as completed by HackuJacku** 2021-10-15 19:35 UTC
Labels: pixelmon, griefdefender
