### ISSUE TITLE
/sts bug

### ISSUE THREAD

**Issue by RedPandaBananna** [SmashMC-Development/Bugs-and-Issues#1037] opened 2022-01-11 19:14 UTC
whenever I type in  the command /sts it provides me a message from 'GTS' saying 'you can't do that'

It has been really confusing and has work for me on other servers.

The server with the bug is the 'Rayquaza' Server

This command is suppose to let you sell your Pokémon you no longer want directly to the server.

N/A - Screenshots

Other people did not seem to have the same problem when I asked them, however it still hinders me.

**Comment by Dxhcky** [comment] 2022-01-11 20:13
/sts isn't a thing at the moment, the command was removed but it should be added back eventually

**Comment by Mikirae** [comment] 2022-01-12 05:14
This is not a bug and is intentional, so I'll be closing this ticket. Thank you for reporting, though :)

**Closed as completed by Mikirae** 2022-01-12 05:14 UTC
