### ISSUE TITLE
GTS

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Bugs-and-Issues#1039] opened 2022-01-12 20:08 UTC
**Describe the Bug**
Pokemon / items on gts being displayed as something else 

**To Reproduce**
1. Go to rayquaza
2. Click on gts
3. Scroll down to a pokemon / item
4. See error (different than expecting) 

**Servers with the Bug**
Rayquaza (could be others) 

**Expected behavior**
Show the right description / picture and for it to not be mixed randomly 

**Screenshots**
![Minecraft 1 12 2 12_01_2022 20_05_33](https://user-images.githubusercontent.com/86555718/149213964-53aef100-21a3-4046-a9ce-165a0cdca58b.png)

![Minecraft 1 12 2 12_01_2022 20_05_46](https://user-images.githubusercontent.com/86555718/149213971-20b6b20c-ad8c-4ad5-9a26-2bc3eb41e179.png)

![Minecraft 1 12 2 12_01_2022 20_05_53](https://user-images.githubusercontent.com/86555718/149213975-e2aae2ea-c09d-42df-a559-f1a9029a1d4e.png)

![Minecraft 1 12 2 12_01_2022 20_05_59](https://user-images.githubusercontent.com/86555718/149213980-67682f8e-0cbc-4cdc-aad8-a77291cbd13c.png)

**Comment by HackuJacku** [comment] 2022-01-14 10:30
Duplicate of #1029

**Closed as completed by HackuJacku** 2022-01-14 10:30 UTC
