### ISSUE TITLE
Broken/dropped items are not able to be picked up

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Bugs-and-Issues#91] opened 2021-05-06 12:14 UTC
**Describe the Bug**
I was in /ic grabbing something (had to break) and the thing did not go into my inventory, I had an empty inventory so it had nothing to do with it being full. Also, on numerous events players report their crate rewards dropping and them not being able to pick it up despite inventory storage not being an issue.

**To Reproduce**
Unsure how to reproduce this as it's not always consistent. (3/3 I did it, this happened to me. Unsure if this is player side or server side)

**Servers with the Bug**
Giratina, Dialga, Darkrai (possibly all)

**Expected behavior**
Dropped/broken items should be able to be picked up if inventory has enough empty slots.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rasgnarok** [comment] 2021-05-20 23:15
"I was in /ic grabbing something (had to break) and the thing did not go into my inventory, I had an empty inventory so it had nothing to do with it being full. "
This makes me think that it's just out of sync with Sponge, not an actual bug unless the server is lagging. Can it be reproduced consistently, every time, in a specific claim?

**Comment by CaretsPuppy** [comment] 2021-05-21 00:45
I am unable to reproduce this, I have changed numerous factors every time I've attempted to test this myself. It seems to perhaps be a server side issue, like lag for example.

**Comment by Rasgnarok** [comment] 2021-05-23 20:10
Yeah, it definitely is lag-related. Closing since this is a sync-out server side, not much we can other than improving performance.

**Closed by Rasgnarok** 2021-05-23 20:10 UTC
Labels: griefdefender, low priority, requires testing, sponge
