### ISSUE TITLE
Daily server restart wipes all votes back to 300

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Bugs-and-Issues#715] opened 2021-11-04 04:23 UTC
**Describe the Bug**
Everyday on the Groudon server it restarts at 12:05am (est) to help clear lag and all that which is great. But I've noticed that we'd have like 90 something votes left till vote party then when we get back online the vote count is back to 300 :[

**To Reproduce**
1.  Log on the groudon server before 12:05am (est) and look at how many votes there are
2.  Log back onto the groudon server after the daily reset and see that voteparty now needs 300 votes again

**Servers with the Bug**
I only play on groudon so I am unsure if this happens on every server. My guess is if any server goes down for a restart the vote party will be automatically reset as well.

**Expected behavior**
All votes on said server that restarts will be reset to require 300 for vote party to happen.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment] 2021-11-04 19:56
Duplicate of #661

**Closed as completed by HackuJacku** 2021-11-04 19:56 UTC
