### ISSUE TITLE
Breeding in general is broken

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Bugs-and-Issues#1314] opened 2022-06-16 04:04 UTC
I've been breeding for a few days now, and suffice to say its broken

1st: Eggs don't show up in the breeding block after it has finished bredding
2nd: Hatching them are glitched visually, after finishing hatching them they still show up in the party as eggs, and when you move them they turn to the pokemon, plus there is no indication in chat that the egg/s hatched.
3rd: the absolute minimum time for an egg to appear in the breedin block is not correct, it's supposed to be 37 1/2 minutes if both pokemon have the "falls madly in love" indication if you right click them, but I timed my pokemon and it took over that, it took 53 mins~ for a "falls madly in love" mons to make an egg, which is absolutely not correct.

Hopefully this gets fixed as breeding in general is not working

**Comment by Mikirae** [comment] 2022-06-21 06:01
The first two sound like a Pixelmon bug
The third one might be caused by the ticks of the server being lower than typical due to the lag that's going on. That will hopefully be resolved soon as we're constantly implementing measures to reduce the lag on the servers.

**Comment by jantjewieger** [comment] 2022-08-17 22:23
Closing this up as breeding has been completely redone with the 9.0.7 update and these are no longer issues

**Closed as completed by jantjewieger** 2022-08-17 22:23 UTC
