### ISSUE TITLE
Safeplace Bug

### ISSUE THREAD

**Issue by arjun-gangwar** [SmashMC-Development/Bugs-and-Issues#308] opened 2021-06-19 11:05 UTC
**Describe the Bug**
Players are able to safeplace while running.

**To Reproduce**
1. execute /safeplace
2. run
3. the command still executes
4. you reach a safeplace

**Servers with the Bug**
Tested on Deoxys.

**Expected behavior**
It should ideally cancel the tp on movement

**Screenshots**
N/A

**Additional context**
N/A

**Comment by HackuJacku** [comment] 2021-06-19 19:50
Duplicate of #204

**Closed as completed by HackuJacku** 2021-06-19 19:50 UTC
Labels: duplicate
