### ISSUE TITLE
quest issues

### ISSUE THREAD

**Issue by LeNoope** [SmashMC-Development/Bugs-and-Issues#161] opened 2021-05-21 20:57 UTC
hi i  killed a strike pokemon for one of my quests but it didnt register i am just wondering if you can do anything about it? the name of the quest i was doing is enigmatic eagle

https://user-images.githubusercontent.com/84600550/119197349-7dda3f00-ba7f-11eb-967b-c5710291aa54.mp4

**Comment by HackuJacku** [comment] 2021-05-27 16:53
LeNoope  - this is not a bug. With the Galarian Zapdos quest, after you defeat an Ashen-form there is a chance that the quest will progress and spawn the Galarian Zapdos or make you defeat more Ashen forms. 

I will be increasing the chance of the Galarian Zapdos spawning - please keep an eye on the changelogs.

**Closed by HackuJacku** 2021-05-27 16:53 UTC
Labels: low priority, pixelmon
