### ISSUE TITLE
Galar quest

### ISSUE THREAD

**Issue by Fazma212** [SmashMC-Development/Bugs-and-Issues#207] opened 2021-05-26 21:30 UTC
the Galar quest wont progress after you kill the ashen/alter forms. I killed a alter salamance for the galar quest and it didnt progress which i thought it would, i was on deoxys.

**Comment by HackuJacku** [comment] 2021-05-27 16:52
@Fazma212 - this is not a bug. With the Galarian Moltres quest, after you defeat an Ashen-form there is a chance that the quest will progress and spawn the Galarian Moltres or make you defeat more Ashen forms. 

I will be increasing the chance of the Galarian Moltres spawning - please keep an eye on the changelogs.

**Comment by HackuJacku** [comment] 2021-05-27 16:52
Please also follow the template provided in the future.

**Closed as completed by HackuJacku** 2021-05-27 16:52 UTC
