### ISSUE TITLE
Specific Pokemon Paper (Galarian Darmanitan)

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#436] opened 2021-08-23 00:51 UTC
**Describe the Bug**
Unable to claim Galarian Darmanitan from Specific Pokemon Paper.

**To Reproduce**
1. Go to Any Server
2. Try /rewardclaim Darmanitan Galarian
3. Says "Galarian Form not Valid"

**Servers with the Bug**
All

**Expected behavior**
Should be able claim Galarian Darmanitan as it is not a Legendary pokemon.

**Screenshots**

https://user-images.githubusercontent.com/84816052/130376107-cb0ef6db-e728-4714-85d9-c02236e95454.mp4

**Additional context**
N/A

**Comment by HackuJacku** [comment] 2021-08-23 15:07
Duplicate of #328

**Closed as completed by HackuJacku** 2021-08-23 15:07 UTC
Labels: duplicate
