### ISSUE TITLE
link to texture pack not working

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Bugs-and-Issues#872] opened 2021-11-29 15:56 UTC
**Describe the Bug**
When you do /textures you get sent a link to the texture pack.
However when u click the link it sends you to a website and says 'Error 404'

**To Reproduce**
go to any server
type /textures
click link
get error

**Servers with the Bug**
All

**Expected behavior**
I would expect to get a working link to download the texture pack

**Screenshots**
Its in dutch but 'fout' means 'error'
![image](https://user-images.githubusercontent.com/87021826/143900407-26df9d61-8985-441c-ab7e-0793846a4f14.png)

**Additional context**
NA

**Comment by HackuJacku** [comment] 2021-11-29 15:58
Where did you get the link? It's not hosted on Dropbox anymore - find the download link in our #smashmc-info channel in Discord.

**Comment by HackuJacku** [comment] 2021-12-01 10:58
Duplicate of #873

**Closed as completed by HackuJacku** 2021-12-01 10:58 UTC
