### ISSUE TITLE
Nether Portals not working

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Bugs-and-Issues#264] opened 2021-06-05 18:02 UTC
**Describe the Bug**
Cannot access nether through portal

**To Reproduce**
1. Make a Nether Portal
2. Try to enter it and nothing will happen
**Servers with the Bug**
Only Tested on Darkrai

**Expected behavior**
To be able enter the Nether

**Screenshots**
![image](https://user-images.githubusercontent.com/84816052/120901072-7777c580-c630-11eb-9d26-fffe7b0bf377.png)
![image](https://user-images.githubusercontent.com/84816052/120901075-7c3c7980-c630-11eb-9f6e-ecd4c7adf00b.png)

**Additional context**
N/A

**Comment by Mikirae** [comment] 2021-06-06 00:24
We think that this is due to cosmetics and should be fixed soon :)

**Comment by HackuJacku** [comment] 2021-06-06 19:25
@M1n0j - is this now fixed please?

**Comment by M1n0j** [comment] 2021-06-07 18:21
they still arent working

**Comment by Mikirae** [comment] 2021-06-10 06:55
@HackuJacku I think we need to have Waterdude detect entrance to the portal and then use Minecraft's Nether Coordinate formula to then transport them to the Nether upon contact with the portal so that it would basically operate the same as a normal Nether Portal. This seems, to me, like a decent work around idea.

**Comment by HackuJacku** [comment] 2021-06-10 12:12
@Mikirae - spoke to Sam yesterday. It's caused by the cosmetics, unequipping the armour stand fixes the issue but asked for a better solution to be worked on today.

**Comment by HackuJacku** [comment] 2021-06-10 14:33
Commit 7f77a4b should fix the issue - part of the next version.

**Comment by HackuJacku** [comment] 2021-06-10 15:49
Fixed from next reboot.

**Closed as completed by HackuJacku** 2021-06-10 15:49 UTC
Labels: requires testing, pixelmon
