### ISSUE TITLE
Able to have no pokemon in your party with /sts

### ISSUE THREAD

**Issue by Shoji007** [SmashMC-Development/Bugs-and-Issues#118] opened 2021-05-15 07:49 UTC
**Describe the Bug**
you are able to /sts the final pokemon in your party to have no pokemon in your party

**To Reproduce**
have one pokemon in your party
/sts it

**Servers with the Bug**
Dialga but pretty sure all

**Expected behavior**
make /sts not able to sts your final mon in your party

**Screenshots**
https://cdn.discordapp.com/attachments/843031425186922516/843032057415598080/unknown.png

**Additional context**
not my screenshot

**Comment by HackuJacku** [comment] 2021-05-17 18:22
After testing this as part of the update for 8.2, I have been unable to reproduce this as seen below.

![image](https://user-images.githubusercontent.com/18508413/118537735-3da85300-b745-11eb-8c1e-70967cdfeee0.png)

**Comment by Rasgnarok** [comment] 2021-05-20 18:34
Closing, as this is solved.

**Closed by Rasgnarok** 2021-05-20 18:34 UTC
Labels: pixelmon, requires testing
