### ISSUE TITLE
/buymove knock off

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#180] opened 2021-05-22 22:38 UTC
**Describe the Bug**
/buymove knock off wont allow scizor to learn it

**Servers with the Bug**
Jirachi

**Expected behavior**
Scizor can learn knock off

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.
![2021-05-22_23 29 35](https://user-images.githubusercontent.com/83971987/119242526-6b7f0480-bb56-11eb-8cf0-9073000c8950.png)

**Comment by Rasgnarok** [comment] 2021-05-23 22:35
Duplicate of #181

**Closed by Rasgnarok** 2021-05-23 22:35 UTC
Labels: custom dev, duplicate, pixelmon
